[package]
name = "parse"
version = "0.1.0"
edition = "2021"

[dependencies]
ast = { version = "0.1.0", path = "../ast" }
lex = { version = "0.1.0", path = "../lex" }
source_idx = { version = "0.1.0", path = "../source_idx" }
unicode-normalization = "0.1.23"
